### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by dimitrisgkoris** [githubteacher/developers-jun-2016-emea#103]
Hello the login failed and I can't push my file.

**Comment by dimitrisgkoris** [comment]
Here is the output

dgkoris@TAG-336 MINGW64 ~/Git/training/developers-jun-2016-emea (dimitrisgkoris-Thessaloniki)
$ git push
Everything up-to-date

dgkoris@TAG-336 MINGW64 ~/Git/training/developers-jun-2016-emea (dimitrisgkoris-Thessaloniki)
$ git status
On branch dimitrisgkoris-Thessaloniki
Your branch is up-to-date with 'origin/dimitrisgkoris-Thessaloniki'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   dimitrisgkoris-Thessaloniki.md

**Comment by ariestiyansyah** [comment]
run this command if you want to push new branch to remote github repo.

$ git push origin dimitrisgkoris-Thessaloniki

**Comment by dimitrisgkoris** [comment]
no worries.. I forgot to commit first. Thanks. :)
